### ISSUE TITLE
Research

### ISSUE THREAD

**Issue by tvhoang91** [tvhoang91/nta-crawler-wordpress-plugin#1]
### Tasks
- [x] https://thachpham.com/series/lap-trinh-plugin-wordpress
- [x] CRUD Custom post type plugin 
- [x] Add key/ read code (ol_scrapes)
- [x] Review PHP (curl)

### wordpress links
- https://codex.wordpress.org/Plugin_Resources
- https://developer.wordpress.org/plugins/
- https://codex.wordpress.org/Plugin_API
- https://make.wordpress.org/core/handbook/best-practices/core-apis/

### wordpress Preference
- https://developer.wordpress.org/reference/
- https://codex.wordpress.org/Plugin_API/Action_Reference
- https://codex.wordpress.org/Plugin_API/Filter_Reference

### php Preference
- http://php.net/manual/en/indexes.functions.php
- http://php.net/manual/en/book.curl.php
